---
- hosts: master
  roles:
    - role: k3s_install_master
- hosts: workers
  become: yes
  vars:
    ansible_become_password: "{{ ansible_password }}"
  roles:
    - role: k3s_install_agent
  vars:
    k3s_token: "{{ lookup('file', '/var/lib/rancher/k3s/server/node-token') }}"
