---
- name: Remove K3s directory
  file:
    path: /var/lib/rancher/k3s
    state: absent
    recurse: yes

- name: Delete K3s related binaries from /usr/local/bin
  file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  loop:
    - crictl
    - k3s
    - k3s-killall.sh
    - kubectl
  become: yes
  tags: remove_binaries

- name: Install K3s binary
  become: yes 
  copy:
    src: k3s
    dest: /usr/local/bin/k3s
    mode: '0755'

- name: Copy the script to the machine
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: '0755'

- name: Run the install script on localhost
  shell: |
        INSTALL_K3S_SKIP_DOWNLOAD=true /tmp/install.sh

- name: Wait for K3s to start
  pause:
    seconds: 10 

- name: Get nodes using kubectl
  shell: kubectl get nodes
  register: kubectl_output
  until: "'Ready' in kubectl_output.stdout"
  retries: 30
  delay: 10

- name: Display kubectl output
  debug:
    msg: "{{ kubectl_output.stdout_lines | join('\n ') }}"
